# Generated by Django 5.1.1 on 2024-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50, null=True)),
                ("dob", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "author",
                "indexes": [
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="author_first_n_16afb3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("published_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", to="library_api.author"
                    ),
                ),
            ],
            options={
                "db_table": "book",
                "indexes": [
                    models.Index(
                        fields=["title", "published_date"], name="book_title_ed8945_idx"
                    )
                ],
            },
        ),
    ]
